# Generated by Django 3.0.8 on 2020-07-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apelido',
            field=models.CharField(default='Lu', max_length=15),
            preserve_default=False,
        ),
    ]
