# Generated by Django 3.0.8 on 2020-07-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200704_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assunto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Assunto'),
            preserve_default=False,
        ),
    ]
