# Generated by Django 3.0.8 on 2020-07-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_assunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assunto',
        ),
    ]
