# Generated by Django 3.0.8 on 2020-07-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200704_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='assunto',
        ),
        migrations.DeleteModel(
            name='Assunto',
        ),
    ]
