# Generated by Django 3.0.8 on 2020-07-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200704_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RlcAssunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Assunto')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='assunto',
            field=models.ManyToManyField(to='blog.RlcAssunto'),
        ),
    ]
