# Generated by Django 3.0.8 on 2020-07-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200704_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rlcassunto',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='post',
            name='assunto',
        ),
        migrations.DeleteModel(
            name='Assunto',
        ),
        migrations.DeleteModel(
            name='RlcAssunto',
        ),
    ]
