# Generated by Django 3.0.8 on 2020-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200704_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='eh_menu',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
