# Generated by Django 3.0.8 on 2020-07-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200717_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
