# Generated by Django 3.0.8 on 2020-07-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_autor_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='pic',
            field=models.ImageField(default='/statis/blog/pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
