# Generated by Django 3.0.8 on 2020-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200718_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gostaram',
            field=models.ManyToManyField(related_name='post_gostaram', to='blog.Autor'),
        ),
    ]
